thrift_library(
  name = 'if',
  srcs = {
    'calculator.thrift' : [
      'Calculator',
    ],
  },
  cpp2_options = [
    'optionals',
    'terse_writes',
    'frozen2',
  ],
  visibility = [
    'PUBLIC',
  ],
)

